app1/urls.py
from django.urls import path
from app1.views import *
app_name='raja'
urlpatterns=[
    path('chinnu/',chinnu,name='chinnu'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='rani'
urlpatterns=[
    path('kutty/',kutty,name='kutty'),
]

project19/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def chinnu(request):
    return render(request,'chinnu.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def kutty(request):
    return render(request,'kutty.html')

templates/chinnu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome to chinnu page</h1>
        <a href="{% url 'rani:kutty' %}"> click hear go to kutty</a>
    </center>
</body>
</html>

templates/kutty.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
       <h1> welcome to kutty page</h1>
       <a href="{% url 'raja:chinnu' %}">click hear to go chinnu</a>
    </center>
</body>
</html>